# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: etl.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'etl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tetl.proto\x12\x03\x65tl\">\n\x06\x45vento\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x17\n\x0ftimestamp_envio\x18\x03 \x01(\x03\"F\n\tResultado\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tresultado\x18\x02 \x01(\t\x12\x1a\n\x12timestamp_resposta\x18\x03 \x01(\x03\x32<\n\nETLService\x12.\n\x0fProcessarEvento\x12\x0b.etl.Evento\x1a\x0e.etl.Resultadob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'etl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTO']._serialized_start=18
  _globals['_EVENTO']._serialized_end=80
  _globals['_RESULTADO']._serialized_start=82
  _globals['_RESULTADO']._serialized_end=152
  _globals['_ETLSERVICE']._serialized_start=154
  _globals['_ETLSERVICE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
